version: '3.8'

services:
  container1:
    image: nginx
    networks:
      - my_network
    container_name: container1
    ports:
      - "8081:80" 

  container2:
    image: nginx
    networks:
      - my_network
    container_name: container2
    ports:
      - "8082:80" 

networks:
  my_network:
    driver: bridge
